apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: filestash
  name: filestash
spec:
  ports:
  - port: 8334
    protocol: TCP
    targetPort: 8334
  selector:
    app: filestash
  type: LoadBalancer
