apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: filestash
  name: filestash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filestash
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: filestash
    spec:
      containers:
      - name: filestash
        image: machines/filestash
        ports:
        - containerPort: 8334
      - name: onlyoffice
        image: onlyoffice/documentserver
        ports:
        - containerPort: 80
