apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: minio
  name: minio
spec:
  ports:
  - name: port-1
    port: 9000
    protocol: TCP
    targetPort: 9000
  - name: port-2
    port: 9001
    protocol: TCP
    targetPort: 9001
  selector:
    app: minio
  type: LoadBalancer
